-- VHDL netlist generated by SCUBA ispLever_v72_SP1_Build (24)
-- Module  Version: 3.6
--X:\Programme\ispTOOLS_72\ispfpga\bin\nt\scuba.exe -w -n adc_ch_in -lang vhdl -synth synplify -bus_exp 7 -bb -arch ep5m00 -type iol -mode in -width 1 -gear 1 -del 16 -e 

-- Fri Apr 24 11:41:10 2009

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library ecp2m;
use ecp2m.components.all;
-- synopsys translate_on

entity adc_ch_in is
    port (
        Del: in  std_logic_vector(3 downto 0); 
        ECLK: in  std_logic; 
        SCLK: in  std_logic; 
        Rst: in  std_logic; 
        Data: in  std_logic_vector(0 downto 0); 
        Q: out  std_logic_vector(1 downto 0));
 attribute dont_touch : string;
 attribute dont_touch of adc_ch_in : entity is "true";
end adc_ch_in;

architecture Structure of adc_ch_in is

    -- internal signal declarations
    signal scuba_vhi: std_logic;
    signal Data_t0: std_logic;
    signal buf_Data0: std_logic;

    -- local component declarations
    component VHI
        port (Z: out  std_logic);
    end component;
    component IB
        port (I: in  std_logic; O: out  std_logic);
    end component;
    component IDDRFXA
        port (D: in  std_logic; CLK1: in  std_logic; CLK2: in  std_logic; 
            CE: in  std_logic; RST: in  std_logic; QA: out  std_logic; 
            QB: out  std_logic);
    end component;
    component DELAYB
        port (A: in  std_logic; DEL0: in  std_logic; DEL1: in  std_logic; 
            DEL2: in  std_logic; DEL3: in  std_logic; Z: out  std_logic);
    end component;
    attribute syn_noprune : boolean;
    attribute syn_noprune of Structure : architecture is true;

begin
    -- component instantiation statements
    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    ud_0: IDDRFXA
        port map (D=>Data_t0, CLK1=>ECLK, CLK2=>SCLK, CE=>scuba_vhi, 
            RST=>Rst, QA=>Q(0), QB=>Q(1));

    udel_0: DELAYB
        port map (A=>buf_Data0, DEL0=>Del(0), DEL1=>Del(1), DEL2=>Del(2), 
            DEL3=>Del(3), Z=>Data_t0);

    buf_Data0_in_inst: IB
        port map (I=>Data(0), O=>buf_Data0);

end Structure;

-- synopsys translate_off
library ecp2m;
configuration Structure_CON of adc_ch_in is
    for Structure
        for all:VHI use entity ecp2m.VHI(V); end for;
        for all:IB use entity ecp2m.IB(V); end for;
        for all:IDDRFXA use entity ecp2m.IDDRFXA(V); end for;
        for all:DELAYB use entity ecp2m.DELAYB(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
